name: Pandas memory issue reproducer

on:
  workflow_dispatch:

jobs:
  run:
    name: Run reproducer
    runs-on: [self-hosted, macos-13]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements.txt
        run: python -m pip install -r requirements.txt
      - name: Run script
        run: mprof run xyz.py
